
spring:
  application:
    name: "food-service"
  datasource:
    url: jdbc:mysql://localhost:3306/jb2404?useSSL=false&serverTimezone=UTC
    username: root
    password: "{cipher}69405dab1e08d1c8865e78891a9f12bae73be55bbc0f2166536fde621b26ae7d"
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # Options: none, update, create, create-drop
    show-sql: true 
  config:
    import: "optional:configserver:http://localhost:9096/"
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone:http://localhost:8761/eureka/
      
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
      
      
server:
  port: 9092

info:
  app:
   name: "FOOD-SERVICE"
   description: "This is api gateway for common entry point"
   version: "{cipher}2de5ab68362fad6f519c775d404db9a744620b2d2632bbde3f8a74461c612928274c36d579ebd8f9a91b0c2a5119b53ba39e30812e6ba47bd9523743ab577175"
      
